spring:
  config:
    import:
      - optional:classpath:structure/stacks.yml
      - optional:classpath:config/gitflow.yml
  application:
    name: dashboard-radar
  datasource:
    url: ${DB_URL:jdbc:h2:mem:dashboard_radar;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO
    com.example.dashboardradar: DEBUG

dashboard:
  github:
    token: ${GITHUB_TOKEN:}
    organization: ${GITHUB_ORG:}
    base-url: https://api.github.com
    page-size: 100
  gitlab:
    token: ${GITLAB_TOKEN:}
    group: ${GITLAB_GROUP:}
    base-url: https://gitlab.com/api/v4
    page-size: 100
    include-subgroups: true
  sources:
    enabled-providers: ${SCM_PROVIDERS:github}
  obsolescence:
    matrix-base-path: classpath:obsolescence
